excluded:
  - Build
  - DerivedData
  - Pods
  - build
  - .build
  - Motive.xcodeproj

# Rule configuration
file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true

# Disabled rules (too noisy for existing codebase)
disabled_rules:
  - trailing_comma
  - opening_brace
  - identifier_name
  - large_tuple
  - force_cast
  - nesting
  - cyclomatic_complexity
  - type_name
  - todo

# Opt-in rules
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - unused_import
